# Versions utilisées dans le projet TechPlus
# Ce fichier centralise les versions pour éviter les incohérences

# Versions principales
node_version: '24'
flutter_version: '3.35.4'
dart_version: '3.9.2'

# Versions des services
postgres_version: '17'
redis_version: '8'

# Versions des outils de développement
typescript_version: '^5.9.2'
jest_version: '^30.1.3'
eslint_version: '^9.36.0'
prettier_version: '^3.6.2'

# Versions des dépendances principales
express_version: '^5.1.0'
prisma_version: '^6.16.2'
stripe_version: '^18.5.0'
nodemailer_version: '^7.0.6'

# Versions Flutter
flutter_riverpod_version: '^2.6.1'
go_router_version: '^16.2.1'
dio_version: '^5.9.0'
google_fonts_version: '^6.3.1'

# Versions des actions GitHub
actions_checkout_version: 'v4'
actions_setup_node_version: 'v4'
flutter_action_version: 'v2'
docker_setup_buildx_version: 'v3'
docker_build_push_version: 'v5'
